apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: default
  labels:
    app: backend-api
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: idp-platform
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
