apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-api
  namespace: default
  labels:
    app: backend-api
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/part-of: idp-platform
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
